name: git_salt_box
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.14.0 <3.0.0"

publish_to: none

dependencies:
  dart_git:
    git: https://github.com/GitJournal/dart_git.git
    # path: ../dart-git
  pinenacl: any

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
