name: git_salt_box
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.14.0 <3.0.0"

publish_to: none

dependencies:
  buffer: ^1.1.1
  collection: ^1.15.0
  dart_git:
    git: https://github.com/GitJournal/dart_git.git
    # path: ../dart-git/
  pinenacl: ^0.3.3
  sodium: ^1.2.0

dev_dependencies:
  import_sorter: ^4.6.0
  lints: ^1.0.0
  test: ^1.16.0

import_sorter:
  comments: false
